default:
  adapter: sqlite3
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  timeout: 5000
development:
  adapter: sqlite3
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  timeout: 5000
  database: storage/development.sqlite3
test:
  adapter: sqlite3
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  timeout: 5000
  database: storage/test.sqlite3
production:
  primary:
    adapter: sqlite3
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
    database: storage/production.sqlite3
  cache:
    adapter: sqlite3
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    adapter: sqlite3
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    adapter: sqlite3
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
